parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $cookieCategories: '%cb_cookie_consent.categories%'
      $useLogger: '%cb_cookie_consent.use_logger%'
      $httpOnly: '%cb_cookie_consent.http_only%'
      $formAction: '%cb_cookie_consent.form_action%'
      $csrfProtection: '%cb_cookie_consent.csrf_protection%'
      $cookieConsentDisabledRoutes: '%cb_cookie_consent.disabled_routes%'

  Chanondb\CookieConsentBundle\:
    resource: '../../'
    exclude: '../../{vendor}'

  Chanondb\CookieConsentBundle\Controller\:
    resource: '../../Controller/*'
    public: true

  Chanondb\CookieConsentBundle\Cookie\CookieChecker:
    arguments: ["@=service('request_stack').getCurrentRequest()"]

  Chanondb\CookieConsentBundle\Cookie\CookieLogger:
    arguments:
      $request: "@=service('request_stack').getCurrentRequest()"
